# Generated by Django 3.2.7 on 2021-09-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=225)),
                ('subtitel', models.CharField(max_length=225)),
                ('button_text', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='media/slider/%y/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
