# Generated by Django 3.2.7 on 2021-09-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('role', models.CharField(max_length=225)),
                ('fb_link', models.CharField(max_length=225)),
                ('insta_link', models.CharField(max_length=225)),
                ('photo', models.ImageField(upload_to='media/team/%y/%d')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
