# Generated by Django 3.2.7 on 2021-09-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/ytubers/%y/%d')),
                ('video_url', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('age', models.IntegerField()),
                ('hight', models.IntegerField()),
                ('crew', models.CharField(max_length=225)),
                ('camera_type', models.CharField(max_length=225)),
                ('sub_count', models.CharField(max_length=225)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=225)),
            ],
        ),
    ]
